name = "CombinedParsers"
uuid = "5ae71ed2-6f8a-4ed1-b94f-e14e8158f19e"
authors = ["Gregor Kappler"]
version = "0.1.2"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
InternedStrings = "7d512f48-7fb1-5a58-b986-67e6dc259f01"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
TextParse = "e0df1984-e451-5cb5-8b61-797a481e67e3"
Tries = "666c268a-d78f-417b-b45a-09e10b365109"

[compat]
AbstractTrees = "0.2.1, 0.3.3"
AutoHashEquals = "0.2.0"
InternedStrings = "0.7"
Nullables = "1.0.0"
TextParse = "0.9, 1.0.0"
Tries = "0.1.4"
julia = "1.3, 1.4, 1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
